export { default as browser } from './lib/browser'
export { toArray, getType, hash } from './lib/lang'
export { assign, omit } from './lib/json'
export { isArray, isBool, isBlob, isEmpty, isFunc, isString, isNumber } from './lib/type'
export { default as verify } from './lib/plugs/verify'
export { default as PreLoad } from './lib/plugs/PreLoad'
export { default as wxPay } from './lib/plugs/wxPay'