export { default as browser } from './lib/browser'
export { observer } from './lib/extends'
export { toArray, getType, hash } from './lib/lang'
export { assign, omit } from './lib/json'
export { isArray, isBool, isBlob, isEmpty, isEmptyObject, isFunc, isString, isNumber } from './lib/type'
export { verify, PreLoad, wxPay, scrollLock } from './lib/plugs'