export { default as isArray } from './isArray'
export { default as isBlob } from './isBlob'
export { default as isBool } from './isBool'
export { default as isEmpty } from './isEmpty'
export { default as isFunc } from './isFunc'
export { default as isNumber } from './isNumber'
export { default as isString } from './isString'
